### ISSUE TITLE
Build Error: Ros Humble + Gazebo Fortress

### ISSUE THREAD

**Issue by DavideLanzoniSacmi** [gazebosim/ros_gz_project_template#11]
## Environment
* OS Version: Ubuntu 22.04
* Gazebo Fortress 

## Description
* Expected behavior: Using `colcon build --cmake-args -DBUILD_TESTING=ON` should build without errors
* Actual behavior: CMake file in `ros_gz_example_gazebo` looks for gz-cmake3 which is included only in gazebo Garden, but there is no branch for Fortress as template. In the CMake other packages from Garden are required. The actual suggested combination of ROS and Gazebo are Humble + Garden, so why should this template use only Garden? What should I use as template for Gazebo Fortress?

## Steps to reproduce
1. Install gazebo for ROS humble (https://gazebosim.org/docs/fortress/ros_installation):
`sudo apt-get install ros-humble-ros-gz`

2. Clone this repository under the source folder of a workspace (following https://gazebosim.org/docs/fortress/ros_gz_project_template_guide)
3. colcon build --cmake-args -DBUILD_TESTING=ON

## Output
```
Latitude-5590:~/project_ws$ colcon build --cmake-args -DBUILD_TESTING=ON
Starting >>> ros_gz_interfaces
Starting >>> ros_gz_sim
Starting >>> sdformat_test_files
Starting >>> ros_gz_example_application                                              
Starting >>> ros_gz_example_bringup
Starting >>> ros_gz_example_description                                              
Starting >>> ros_gz_example_gazebo
--- stderr: sdformat_test_files                                                                  
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING


---
Finished <<< sdformat_test_files [1.59s]
Starting >>> sdformat_urdf                                                                       
Finished <<< ros_gz_example_application [1.73s]                                                  
--- stderr: ros_gz_example_gazebo                                                                
CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "Findgz-sim7.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gz-sim7", but
  CMake did not find one.

  Could not find a package configuration file provided by "gz-sim7" with any
  of the following names:

    gz-sim7Config.cmake
    gz-sim7-config.cmake

  Add the installation prefix of "gz-sim7" to CMAKE_PREFIX_PATH or set
  "gz-sim7_DIR" to a directory containing one of the above files.  If
  "gz-sim7" provides a separate development package or SDK, be sure it has
  been installed.


---
Failed   <<< ros_gz_example_gazebo [1.68s, exited with code 1]
Finished <<< ros_gz_example_bringup [1.85s]                                       
Aborted  <<< sdformat_urdf [0.29s]
Aborted  <<< ros_gz_example_description [1.80s]
Aborted  <<< ros_gz_interfaces [3.07s]                                            
Aborted  <<< ros_gz_sim [3.29s]                            

Summary: 3 packages finished [4.54s]
  1 package failed: ros_gz_example_gazebo
  4 packages aborted: ros_gz_example_description ros_gz_interfaces ros_gz_sim sdformat_urdf
  2 packages had stderr output: ros_gz_example_gazebo sdformat_test_files
  10 packages not processed
```

**Comment by jrutgeer** [comment]
> why should this template use only Garden

This is an example repository. Imo it aims at _documenting the concepts_ rather than trying to provide an exact copy-paste solution for each and every version or ROS / Gazebo combination.

>  What should I use as template for Gazebo Fortress?

You have to adapt the `CMakeLists.txt` to correspond to the package releases for Fortress.
They are listed in the [collection-fortress.yaml](https://github.com/gazebosim/gz-fortress/blob/main/gazebodistro/collection-fortress.yaml) file.

E.g. you will have to replace

```cmake
find_package(gz-cmake3 REQUIRED)
find_package(gz-plugin2 REQUIRED COMPONENTS register)
set(GZ_PLUGIN_VER ${gz-plugin2_VERSION_MAJOR})
find_package(gz-common5 REQUIRED COMPONENTS profiler)
set(GZ_COMMON_VER ${gz-common5_VERSION_MAJOR})
find_package(gz-sim7 REQUIRED)
set(GZ_SIM_VER ${gz-sim7_VERSION_MAJOR})
[...]
```

by:

```cmake
find_package(ign-cmake2 REQUIRED)
find_package(ign-plugin1 REQUIRED COMPONENTS register)
set(IGN_PLUGIN_VER ${ign-plugin1_VERSION_MAJOR})
find_package(ign-common4 REQUIRED COMPONENTS profiler)
set(IGN_COMMON_VER ${ign-common4_VERSION_MAJOR})
find_package(ign-gazebo6 REQUIRED)
set(IGN_GAZEBO_VER ${ign-gazebo6_VERSION_MAJOR})
[...]
```

Obviously not just this section, but throughout the remainder of all `CMakeList.txt` files.

Mind also that from Fortress to Garden there has been a rename from "Ignition Gazebo" to "Gazebo Sim" due to trademark issues on the 'Ignition' name. That's e.g. why in above code snippet `gz-sim7` for Garden is replaced by `ign-gazebo6` for Fortress (as opposed to `gz-sim6`).

Also in the code you will have to change many references of `gz` and `sim` into `ign` and `gazebo`. For further documentation see the [gazebosim.org](https://gazebosim.org/docs/harmonic/migration_from_ignition) site.

Anyway, I would not spend the time to try and make this particular repository compile for Fortress. instead, just use it as an example and implement your own code for your project. E.g. start with the [system plugin documentation](https://gazebosim.org/api/sim/6/createsystemplugins.html) for Fortress, try and get that to compile.
The code for that example is in the gz-sim repository (ign-gazebo6 branch), see [here](https://github.com/gazebosim/gz-sim/tree/ign-gazebo6/examples/plugin).

See also [this post](https://community.gazebosim.org/t/gazebo-plugin-video-tutorial-series/1639/7?u=jrtg) on the community forum for more pointers to info on writing Gazebo system plugins.

There is also this upcoming talk at ROSCon2023: [Simulate your World: A deeper look at extending Gazebo](https://roscon.ros.org/2023/#:~:text=Simulate%20your%20World%3A%20A%20deeper%20look%20at%20extending%20Gazebo).

If you have further questions, ask them at the [Robotics Stack Exchange](https://robotics.stackexchange.com/) instead of here.

**Comment by DavideLanzoniSacmi** [comment]
Thanks a lot! Really complete answer. I will dig into it better with your pointers

**Comment by AlfonGio** [comment]
Hi @DavideLanzoniSacmi,

I happened to experience the same error. How are you able to solve all the errors? I try to read the above hints provided but not really sure what to change in the CMakeLists.

Thank you.

**Comment by EyalBrilling** [comment]
I met the same error. Will update if the answer here helps.
I see it happens to a lot of people who use this project, There should be some comment about this in the CMake.

**Comment by AlfonGio** [comment]
@EyalBrilling 
Yeah, changing to ignition seems to solve most of the package issues. But I have another error arise regarding BasicSystem.hh and FullSystem.hh. Did it also happened to you?

![Screenshot from 2024-01-08 11-40-42](https://github.com/gazebosim/ros_gz_project_template/assets/56231194/d832f1d3-4e59-4f99-9e12-5493775c2532)

**Comment by jrutgeer** [comment]
@EyalBrilling 
Yes, it seems the correct name is `ignition-cmake2` instead of `ign-cmake2`.
The yaml file is correct though, as it contains the github repository name and branch:

![2024-01-09 10_35_20-gazebosim_gz-cmake at ign-cmake2](https://github.com/gazebosim/ros_gz_project_template/assets/74099146/6fedf19e-b5b0-48a8-8672-5eecd6e3f19d)

The `CMakeLists.txt` file seems to need rather the corresponding project names, as defined e.g. [here](https://github.com/gazebosim/gz-cmake/blob/f527f37fc86f9197c8b87ed3e524ba9dfc8ee684/CMakeLists.txt#L6).


Anyway, given there appears to be a Fortress branch to this repository now (this thread pre-dates it), the obvious choice is to use that branch, instead of redoing the work.
@AlfonGio same remark: try with the Fortress branch instead.
